### PR TITLE
Fix #109

### LINKED ISSUE #109: Update the Tyche JS and Deactivation survey code as needed.
Describe the bug
There have been some updates to the [Tyche JS](https://github.com/TycheSoftwares/tyche-js-constructor) and [Plugin Deactivation](https://github.com/TycheSoftwares/tyche-plugin-deactivation) repos.

Please update the v2 Plugin Deactivation files in the plugins where they have been implemented in.

### PR DESCRIPTION
**Pull request by nidhitatosaniya**
Updated the Tyche JS and Deactivation class file.
[do-not-scan]

### CODE REVIEW

File: includes/class-tyche-plugin-deactivation.php [hunk 1]
```diff
@@ -117,7 +117,7 @@ public function init_vars( $options ) {
 		public function plugin_action_links( $links ) {
```
Comment (handelce) [inline includes/class-tyche-plugin-deactivation.php:117]: @nidhitatosaniya This file should be in the `includes/component/plugin-deacivation` folder.

**Review by handelce — CHANGES_REQUESTED** [review]

File: includes/class-tyche-plugin-deactivation.php (hunk 1 above)
Comment (handelce) [reply includes/class-tyche-plugin-deactivation.php:117]: > @nidhitatosaniya This file should be in the `includes/component/plugin-deacivation` folder.

@nidhitatosaniya There's a mistake in the file name. It should rather be `includes/component/plugin-deactivation` folder.

**Review by handelce — CHANGES_REQUESTED** [review]
@nidhitatosaniya There's a mistake in the file name. It should rather be `includes/component/plugin-deactivation` folder.

**Review by handelce — APPROVED** [review]
